/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SunumYukleRouteImport } from './routes/sunum-yukle'
import { Route as StartupRouteImport } from './routes/startup'
import { Route as SponsorRouteImport } from './routes/sponsor'
import { Route as ProfilRouteImport } from './routes/profil'
import { Route as NotworkNedirRouteImport } from './routes/notwork-nedir'
import { Route as NetworkingRouteImport } from './routes/networking'
import { Route as NetworkStartupRouteImport } from './routes/network-startup'
import { Route as MatchLabRouteImport } from './routes/match-lab'
import { Route as LinklerRouteImport } from './routes/linkler'
import { Route as LegacyRouteImport } from './routes/legacy'
import { Route as KvkkRouteImport } from './routes/kvkk'
import { Route as FiveRouteImport } from './routes/five'
import { Route as EtkinliklerRouteImport } from './routes/etkinlikler'
import { Route as EtkinlikDegerlendirmeRouteImport } from './routes/etkinlik-degerlendirme'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as CerezPolitikasiRouteImport } from './routes/cerez-politikasi'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AcikRizaRouteImport } from './routes/acik-riza'
import { Route as R21agustosRouteImport } from './routes/21agustos'
import { Route as R14temmuznetworkingRouteImport } from './routes/14temmuznetworking'
import { Route as R14temmuzRouteImport } from './routes/14temmuz'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UUsernameRouteImport } from './routes/u.$username'
import { Route as FiveLiveRouteImport } from './routes/five_.live'
import { Route as R21AgustosWordcloudRouteImport } from './routes/21-agustos.wordcloud'
import { Route as R21AgustosSonuclarRouteImport } from './routes/21-agustos.sonuclar'
import { Route as R21AgustosNetworkRouteImport } from './routes/21-agustos.network'
import { Route as R21AgustosEslesmeRouteImport } from './routes/21-agustos.eslesme'

const SunumYukleRoute = SunumYukleRouteImport.update({
  id: '/sunum-yukle',
  path: '/sunum-yukle',
  getParentRoute: () => rootRouteImport,
} as any)
const StartupRoute = StartupRouteImport.update({
  id: '/startup',
  path: '/startup',
  getParentRoute: () => rootRouteImport,
} as any)
const SponsorRoute = SponsorRouteImport.update({
  id: '/sponsor',
  path: '/sponsor',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilRoute = ProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const NotworkNedirRoute = NotworkNedirRouteImport.update({
  id: '/notwork-nedir',
  path: '/notwork-nedir',
  getParentRoute: () => rootRouteImport,
} as any)
const NetworkingRoute = NetworkingRouteImport.update({
  id: '/networking',
  path: '/networking',
  getParentRoute: () => rootRouteImport,
} as any)
const NetworkStartupRoute = NetworkStartupRouteImport.update({
  id: '/network-startup',
  path: '/network-startup',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchLabRoute = MatchLabRouteImport.update({
  id: '/match-lab',
  path: '/match-lab',
  getParentRoute: () => rootRouteImport,
} as any)
const LinklerRoute = LinklerRouteImport.update({
  id: '/linkler',
  path: '/linkler',
  getParentRoute: () => rootRouteImport,
} as any)
const LegacyRoute = LegacyRouteImport.update({
  id: '/legacy',
  path: '/legacy',
  getParentRoute: () => rootRouteImport,
} as any)
const KvkkRoute = KvkkRouteImport.update({
  id: '/kvkk',
  path: '/kvkk',
  getParentRoute: () => rootRouteImport,
} as any)
const FiveRoute = FiveRouteImport.update({
  id: '/five',
  path: '/five',
  getParentRoute: () => rootRouteImport,
} as any)
const EtkinliklerRoute = EtkinliklerRouteImport.update({
  id: '/etkinlikler',
  path: '/etkinlikler',
  getParentRoute: () => rootRouteImport,
} as any)
const EtkinlikDegerlendirmeRoute = EtkinlikDegerlendirmeRouteImport.update({
  id: '/etkinlik-degerlendirme',
  path: '/etkinlik-degerlendirme',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const CerezPolitikasiRoute = CerezPolitikasiRouteImport.update({
  id: '/cerez-politikasi',
  path: '/cerez-politikasi',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AcikRizaRoute = AcikRizaRouteImport.update({
  id: '/acik-riza',
  path: '/acik-riza',
  getParentRoute: () => rootRouteImport,
} as any)
const R21agustosRoute = R21agustosRouteImport.update({
  id: '/21agustos',
  path: '/21agustos',
  getParentRoute: () => rootRouteImport,
} as any)
const R14temmuznetworkingRoute = R14temmuznetworkingRouteImport.update({
  id: '/14temmuznetworking',
  path: '/14temmuznetworking',
  getParentRoute: () => rootRouteImport,
} as any)
const R14temmuzRoute = R14temmuzRouteImport.update({
  id: '/14temmuz',
  path: '/14temmuz',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UUsernameRoute = UUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const FiveLiveRoute = FiveLiveRouteImport.update({
  id: '/five_/live',
  path: '/five/live',
  getParentRoute: () => rootRouteImport,
} as any)
const R21AgustosWordcloudRoute = R21AgustosWordcloudRouteImport.update({
  id: '/21-agustos/wordcloud',
  path: '/21-agustos/wordcloud',
  getParentRoute: () => rootRouteImport,
} as any)
const R21AgustosSonuclarRoute = R21AgustosSonuclarRouteImport.update({
  id: '/21-agustos/sonuclar',
  path: '/21-agustos/sonuclar',
  getParentRoute: () => rootRouteImport,
} as any)
const R21AgustosNetworkRoute = R21AgustosNetworkRouteImport.update({
  id: '/21-agustos/network',
  path: '/21-agustos/network',
  getParentRoute: () => rootRouteImport,
} as any)
const R21AgustosEslesmeRoute = R21AgustosEslesmeRouteImport.update({
  id: '/21-agustos/eslesme',
  path: '/21-agustos/eslesme',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/14temmuz': typeof R14temmuzRoute
  '/14temmuznetworking': typeof R14temmuznetworkingRoute
  '/21agustos': typeof R21agustosRoute
  '/acik-riza': typeof AcikRizaRoute
  '/admin': typeof AdminRoute
  '/cerez-politikasi': typeof CerezPolitikasiRoute
  '/community': typeof CommunityRoute
  '/etkinlik-degerlendirme': typeof EtkinlikDegerlendirmeRoute
  '/etkinlikler': typeof EtkinliklerRoute
  '/five': typeof FiveRoute
  '/kvkk': typeof KvkkRoute
  '/legacy': typeof LegacyRoute
  '/linkler': typeof LinklerRoute
  '/match-lab': typeof MatchLabRoute
  '/network-startup': typeof NetworkStartupRoute
  '/networking': typeof NetworkingRoute
  '/notwork-nedir': typeof NotworkNedirRoute
  '/profil': typeof ProfilRoute
  '/sponsor': typeof SponsorRoute
  '/startup': typeof StartupRoute
  '/sunum-yukle': typeof SunumYukleRoute
  '/21-agustos/eslesme': typeof R21AgustosEslesmeRoute
  '/21-agustos/network': typeof R21AgustosNetworkRoute
  '/21-agustos/sonuclar': typeof R21AgustosSonuclarRoute
  '/21-agustos/wordcloud': typeof R21AgustosWordcloudRoute
  '/five/live': typeof FiveLiveRoute
  '/u/$username': typeof UUsernameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/14temmuz': typeof R14temmuzRoute
  '/14temmuznetworking': typeof R14temmuznetworkingRoute
  '/21agustos': typeof R21agustosRoute
  '/acik-riza': typeof AcikRizaRoute
  '/admin': typeof AdminRoute
  '/cerez-politikasi': typeof CerezPolitikasiRoute
  '/community': typeof CommunityRoute
  '/etkinlik-degerlendirme': typeof EtkinlikDegerlendirmeRoute
  '/etkinlikler': typeof EtkinliklerRoute
  '/five': typeof FiveRoute
  '/kvkk': typeof KvkkRoute
  '/legacy': typeof LegacyRoute
  '/linkler': typeof LinklerRoute
  '/match-lab': typeof MatchLabRoute
  '/network-startup': typeof NetworkStartupRoute
  '/networking': typeof NetworkingRoute
  '/notwork-nedir': typeof NotworkNedirRoute
  '/profil': typeof ProfilRoute
  '/sponsor': typeof SponsorRoute
  '/startup': typeof StartupRoute
  '/sunum-yukle': typeof SunumYukleRoute
  '/21-agustos/eslesme': typeof R21AgustosEslesmeRoute
  '/21-agustos/network': typeof R21AgustosNetworkRoute
  '/21-agustos/sonuclar': typeof R21AgustosSonuclarRoute
  '/21-agustos/wordcloud': typeof R21AgustosWordcloudRoute
  '/five/live': typeof FiveLiveRoute
  '/u/$username': typeof UUsernameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/14temmuz': typeof R14temmuzRoute
  '/14temmuznetworking': typeof R14temmuznetworkingRoute
  '/21agustos': typeof R21agustosRoute
  '/acik-riza': typeof AcikRizaRoute
  '/admin': typeof AdminRoute
  '/cerez-politikasi': typeof CerezPolitikasiRoute
  '/community': typeof CommunityRoute
  '/etkinlik-degerlendirme': typeof EtkinlikDegerlendirmeRoute
  '/etkinlikler': typeof EtkinliklerRoute
  '/five': typeof FiveRoute
  '/kvkk': typeof KvkkRoute
  '/legacy': typeof LegacyRoute
  '/linkler': typeof LinklerRoute
  '/match-lab': typeof MatchLabRoute
  '/network-startup': typeof NetworkStartupRoute
  '/networking': typeof NetworkingRoute
  '/notwork-nedir': typeof NotworkNedirRoute
  '/profil': typeof ProfilRoute
  '/sponsor': typeof SponsorRoute
  '/startup': typeof StartupRoute
  '/sunum-yukle': typeof SunumYukleRoute
  '/21-agustos/eslesme': typeof R21AgustosEslesmeRoute
  '/21-agustos/network': typeof R21AgustosNetworkRoute
  '/21-agustos/sonuclar': typeof R21AgustosSonuclarRoute
  '/21-agustos/wordcloud': typeof R21AgustosWordcloudRoute
  '/five_/live': typeof FiveLiveRoute
  '/u/$username': typeof UUsernameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/14temmuz'
    | '/14temmuznetworking'
    | '/21agustos'
    | '/acik-riza'
    | '/admin'
    | '/cerez-politikasi'
    | '/community'
    | '/etkinlik-degerlendirme'
    | '/etkinlikler'
    | '/five'
    | '/kvkk'
    | '/legacy'
    | '/linkler'
    | '/match-lab'
    | '/network-startup'
    | '/networking'
    | '/notwork-nedir'
    | '/profil'
    | '/sponsor'
    | '/startup'
    | '/sunum-yukle'
    | '/21-agustos/eslesme'
    | '/21-agustos/network'
    | '/21-agustos/sonuclar'
    | '/21-agustos/wordcloud'
    | '/five/live'
    | '/u/$username'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/14temmuz'
    | '/14temmuznetworking'
    | '/21agustos'
    | '/acik-riza'
    | '/admin'
    | '/cerez-politikasi'
    | '/community'
    | '/etkinlik-degerlendirme'
    | '/etkinlikler'
    | '/five'
    | '/kvkk'
    | '/legacy'
    | '/linkler'
    | '/match-lab'
    | '/network-startup'
    | '/networking'
    | '/notwork-nedir'
    | '/profil'
    | '/sponsor'
    | '/startup'
    | '/sunum-yukle'
    | '/21-agustos/eslesme'
    | '/21-agustos/network'
    | '/21-agustos/sonuclar'
    | '/21-agustos/wordcloud'
    | '/five/live'
    | '/u/$username'
  id:
    | '__root__'
    | '/'
    | '/14temmuz'
    | '/14temmuznetworking'
    | '/21agustos'
    | '/acik-riza'
    | '/admin'
    | '/cerez-politikasi'
    | '/community'
    | '/etkinlik-degerlendirme'
    | '/etkinlikler'
    | '/five'
    | '/kvkk'
    | '/legacy'
    | '/linkler'
    | '/match-lab'
    | '/network-startup'
    | '/networking'
    | '/notwork-nedir'
    | '/profil'
    | '/sponsor'
    | '/startup'
    | '/sunum-yukle'
    | '/21-agustos/eslesme'
    | '/21-agustos/network'
    | '/21-agustos/sonuclar'
    | '/21-agustos/wordcloud'
    | '/five_/live'
    | '/u/$username'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R14temmuzRoute: typeof R14temmuzRoute
  R14temmuznetworkingRoute: typeof R14temmuznetworkingRoute
  R21agustosRoute: typeof R21agustosRoute
  AcikRizaRoute: typeof AcikRizaRoute
  AdminRoute: typeof AdminRoute
  CerezPolitikasiRoute: typeof CerezPolitikasiRoute
  CommunityRoute: typeof CommunityRoute
  EtkinlikDegerlendirmeRoute: typeof EtkinlikDegerlendirmeRoute
  EtkinliklerRoute: typeof EtkinliklerRoute
  FiveRoute: typeof FiveRoute
  KvkkRoute: typeof KvkkRoute
  LegacyRoute: typeof LegacyRoute
  LinklerRoute: typeof LinklerRoute
  MatchLabRoute: typeof MatchLabRoute
  NetworkStartupRoute: typeof NetworkStartupRoute
  NetworkingRoute: typeof NetworkingRoute
  NotworkNedirRoute: typeof NotworkNedirRoute
  ProfilRoute: typeof ProfilRoute
  SponsorRoute: typeof SponsorRoute
  StartupRoute: typeof StartupRoute
  SunumYukleRoute: typeof SunumYukleRoute
  R21AgustosEslesmeRoute: typeof R21AgustosEslesmeRoute
  R21AgustosNetworkRoute: typeof R21AgustosNetworkRoute
  R21AgustosSonuclarRoute: typeof R21AgustosSonuclarRoute
  R21AgustosWordcloudRoute: typeof R21AgustosWordcloudRoute
  FiveLiveRoute: typeof FiveLiveRoute
  UUsernameRoute: typeof UUsernameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sunum-yukle': {
      id: '/sunum-yukle'
      path: '/sunum-yukle'
      fullPath: '/sunum-yukle'
      preLoaderRoute: typeof SunumYukleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/startup': {
      id: '/startup'
      path: '/startup'
      fullPath: '/startup'
      preLoaderRoute: typeof StartupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sponsor': {
      id: '/sponsor'
      path: '/sponsor'
      fullPath: '/sponsor'
      preLoaderRoute: typeof SponsorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil': {
      id: '/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof ProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notwork-nedir': {
      id: '/notwork-nedir'
      path: '/notwork-nedir'
      fullPath: '/notwork-nedir'
      preLoaderRoute: typeof NotworkNedirRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/networking': {
      id: '/networking'
      path: '/networking'
      fullPath: '/networking'
      preLoaderRoute: typeof NetworkingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/network-startup': {
      id: '/network-startup'
      path: '/network-startup'
      fullPath: '/network-startup'
      preLoaderRoute: typeof NetworkStartupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/match-lab': {
      id: '/match-lab'
      path: '/match-lab'
      fullPath: '/match-lab'
      preLoaderRoute: typeof MatchLabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/linkler': {
      id: '/linkler'
      path: '/linkler'
      fullPath: '/linkler'
      preLoaderRoute: typeof LinklerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legacy': {
      id: '/legacy'
      path: '/legacy'
      fullPath: '/legacy'
      preLoaderRoute: typeof LegacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kvkk': {
      id: '/kvkk'
      path: '/kvkk'
      fullPath: '/kvkk'
      preLoaderRoute: typeof KvkkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/five': {
      id: '/five'
      path: '/five'
      fullPath: '/five'
      preLoaderRoute: typeof FiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/etkinlikler': {
      id: '/etkinlikler'
      path: '/etkinlikler'
      fullPath: '/etkinlikler'
      preLoaderRoute: typeof EtkinliklerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/etkinlik-degerlendirme': {
      id: '/etkinlik-degerlendirme'
      path: '/etkinlik-degerlendirme'
      fullPath: '/etkinlik-degerlendirme'
      preLoaderRoute: typeof EtkinlikDegerlendirmeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cerez-politikasi': {
      id: '/cerez-politikasi'
      path: '/cerez-politikasi'
      fullPath: '/cerez-politikasi'
      preLoaderRoute: typeof CerezPolitikasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acik-riza': {
      id: '/acik-riza'
      path: '/acik-riza'
      fullPath: '/acik-riza'
      preLoaderRoute: typeof AcikRizaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/21agustos': {
      id: '/21agustos'
      path: '/21agustos'
      fullPath: '/21agustos'
      preLoaderRoute: typeof R21agustosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/14temmuznetworking': {
      id: '/14temmuznetworking'
      path: '/14temmuznetworking'
      fullPath: '/14temmuznetworking'
      preLoaderRoute: typeof R14temmuznetworkingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/14temmuz': {
      id: '/14temmuz'
      path: '/14temmuz'
      fullPath: '/14temmuz'
      preLoaderRoute: typeof R14temmuzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$username': {
      id: '/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof UUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/five_/live': {
      id: '/five_/live'
      path: '/five/live'
      fullPath: '/five/live'
      preLoaderRoute: typeof FiveLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/21-agustos/wordcloud': {
      id: '/21-agustos/wordcloud'
      path: '/21-agustos/wordcloud'
      fullPath: '/21-agustos/wordcloud'
      preLoaderRoute: typeof R21AgustosWordcloudRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/21-agustos/sonuclar': {
      id: '/21-agustos/sonuclar'
      path: '/21-agustos/sonuclar'
      fullPath: '/21-agustos/sonuclar'
      preLoaderRoute: typeof R21AgustosSonuclarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/21-agustos/network': {
      id: '/21-agustos/network'
      path: '/21-agustos/network'
      fullPath: '/21-agustos/network'
      preLoaderRoute: typeof R21AgustosNetworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/21-agustos/eslesme': {
      id: '/21-agustos/eslesme'
      path: '/21-agustos/eslesme'
      fullPath: '/21-agustos/eslesme'
      preLoaderRoute: typeof R21AgustosEslesmeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R14temmuzRoute: R14temmuzRoute,
  R14temmuznetworkingRoute: R14temmuznetworkingRoute,
  R21agustosRoute: R21agustosRoute,
  AcikRizaRoute: AcikRizaRoute,
  AdminRoute: AdminRoute,
  CerezPolitikasiRoute: CerezPolitikasiRoute,
  CommunityRoute: CommunityRoute,
  EtkinlikDegerlendirmeRoute: EtkinlikDegerlendirmeRoute,
  EtkinliklerRoute: EtkinliklerRoute,
  FiveRoute: FiveRoute,
  KvkkRoute: KvkkRoute,
  LegacyRoute: LegacyRoute,
  LinklerRoute: LinklerRoute,
  MatchLabRoute: MatchLabRoute,
  NetworkStartupRoute: NetworkStartupRoute,
  NetworkingRoute: NetworkingRoute,
  NotworkNedirRoute: NotworkNedirRoute,
  ProfilRoute: ProfilRoute,
  SponsorRoute: SponsorRoute,
  StartupRoute: StartupRoute,
  SunumYukleRoute: SunumYukleRoute,
  R21AgustosEslesmeRoute: R21AgustosEslesmeRoute,
  R21AgustosNetworkRoute: R21AgustosNetworkRoute,
  R21AgustosSonuclarRoute: R21AgustosSonuclarRoute,
  R21AgustosWordcloudRoute: R21AgustosWordcloudRoute,
  FiveLiveRoute: FiveLiveRoute,
  UUsernameRoute: UUsernameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
